// <auto-generated />
namespace Entity_Code_First.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addedmaritial_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmaritial_status));
        
        string IMigrationMetadata.Id
        {
            get { return "202409121056020_added-maritial_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
