// <auto-generated />
namespace Entity_Code_First.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addedcity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcity));
        
        string IMigrationMetadata.Id
        {
            get { return "202409121043207_added-city"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
